<?
session_start();
error_reporting(0);


function get_used_functions_in_code($source) {
    $tokens = token_get_all($source);
    $functions = array();
    $thisStringIsFunc = 0;

    foreach($tokens as $token) {
        if(($token[0]!=T_WHITESPACE)&&((!is_string($token))||($token[0]!='('))) unset($func);
        if((is_array($token))&&(in_array($token[0],array(T_EVAL,T_EXIT,T_INCLUDE,T_INCLUDE_ONCE,T_LIST,T_REQUIRE,T_REQUIRE_ONCE,T_RETURN,T_UNSET)))) {$token[0]=T_STRING;$thisStringIsFunc=1;}
        switch($token[0]) {
            case T_FUNCTION: $thisStringIsFunc=-1;
            break;
            case T_STRING:
                if($thisStringIsFunc>0) {
                    if (!in_array(strtoupper($token[1]),$functionsUp)) {$functions[]=$token[1];$functionsUp[]=strtoupper($token[1]);}
                    $thisStringIsFunc = 0;
                } elseif ($thisStringIsFunc+1>0) {
                    $func = $token[1];
                } else $thisStringIsFunc = 0;

            break;
            case '(':if($func) if(!in_array(strtoupper($func),$functionsUp)) {$functions[]=$func;$functionsUp[]=strtoupper($func);}
        }
    }

    return $functions;
}

function functions_in_file($file) 
{
    $file = join("\n",file($file));
	$x=explode("\n",$file);
	foreach($x as $k=>$v)
	{
		$f=array();
		preg_match('/function\s+(\w+)/', $v, $m);
		if($m[1])
		{
		$functions[$k]=$m[1];
		}
	}
   
   
    return $functions;
}


class fwe
{
	
	function loginform()
	{
		?>
		<html>
		<div>
		<form method="post">
		Логин: <input type="text" name="login" /><br/>
		Пароль: <input type="text" name="pass" /><br/>
		<input type="submit" />
		</form>
		</div>
		</html>
		<?
		
	}
	
	function login()
	{
		if(isset($_GET['out'])){$_SESSION['login']=''; $_SESSION['pass']='';} // выход
		
		if(!$login && isset($_POST['login'])){$login=$_POST['login'];}
		if(!$pass && isset($_POST['pass'])){$pass=$_POST['pass'];}
		 
		if(!$login && isset($_SESSION['login'])){$login=$_SESSION['login'];}
		if(!$pass && isset($_SESSION['pass'])){$pass=$_SESSION['pass'];}
 
		if($pass =='zdctvjue' &&  $login=='admin' )
		{
			//print 'ДОСТУП ПОЛУЧЕН';
			$_SESSION['login'] = $login; $_SESSION['pass'] = $pass; 
			return true;
		}
		else{
			 if($_POST){print 'не верные логин/пароль';}
			$this->loginform();
			return false;
		}
	}
	
	
	function __construct( )
	{
		if(!$this->login()){die();}
		
		$this->top_dir = $_SERVER["DOCUMENT_ROOT"]; // Корень
		$this->top_dir_editor = 'sites/em/sahmatka'; // Редактор относительно корня
		if(isset($_REQUEST['f']))
		{
			$this->fpath = $_REQUEST['f'];
		}
		else{$this->fpath='';}
		
	}




	function get_ftree_jsoon($dir='',$level='0',$max_level='')
	{
		/*
		
		{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : []  // array of strings or objects
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}
нет внутренних рекурсивных иттераций)
*/
		if($dir=='#'){$dir='';}
		$d_one = $dir;
		$top_dir = $this->top_dir;
		// ПЕРВАЯ НАРУЖНАЯ ИТЕРАЦИЯ
		if (!$dir) 
		{	
			// По умолчанию родительская от текущей дирректории
			$dir = str_replace($top_dir, '', __DIR__);
			$dir = str_replace('fwe', '', $dir);
		
			// Задаем корневую
			$dir = $this->top_dir_editor;
			$dir = trim($dir, '/');

			//print $dir;
		}

		$dirx =   $top_dir . '/' . $dir . '/';

		$dir_arr = scandir($dirx);

		 
		foreach ($dir_arr as $k => $file)
		{
 			if ($file != '.' && $file != '..') 
			{
				
				
				
				$datapath = $dir .'/'.$file;
				if( $datapath == $this->fpath ){ $sel = ' tree_file_s ';}else{$sel=''; }
				
				$js_data=array();
				$js_data['id'] = $datapath;
				if(!$d_one){	$js_data['parent'] = '#'; }
				else{$js_data['parent'] = $dir;	}		
				$js_data['text'] = '<span class="fwe_jstree_fn">'.$file.'</span> ';
				 
				// ПЕРЕДАЕМ ДОП АТРИБУТЫ A 
				$a_attr = array();
				 				
				$a_attr['dpath']=$datapath;
			
				//li_attr тоже можно передать
				 
				$state = array();
				$state['selected'] = false;
		
				if (is_dir($dirx . '/' . $file)) 
				{
					$a_attr['dtype'] = 'dir';//Доп аттрибут для api
				 
					//$js_data['icon'] = '123';
					$js_data['children'] = true;
					if($level==0)
					{
						//$state['opened'] = true;
					}
					else{
						// $state['opened'] = false;
					}
					$js_data['type'] = 'dir';
					$js_data['icon'] = 'folder';
			 
				} 
				elseif (is_file($dirx . '/' . $file)) 
				{
					$js_data['type'] = 'file';
					$ext = pathinfo($file, PATHINFO_EXTENSION);
					if($ext)
					{
						$js_data['icon'] = 'file file-'.$ext;
					}
					else
					{
						$js_data['icon'] = 'file file-ewnode';
					}
					$a_attr['dtype'] = 'file';//Доп аттрибут для api
					//$js_data['icon'] = 'fa fa-file fa-large';
					$js_data['children'] = false;
					$state['opened'] = false;
				}
					$js_data['a_attr'] = $a_attr;
				$js_data['state'] = $state;
				$out_js[]=$js_data;
				
				
			}
		}
		return $out_js;
	}
	
	
	
	
	function get_ftree($dir='',$level='0',$max_level='')
	{
		$top_dir = $this->top_dir;
		// ПЕРВАЯ НАРУЖНАЯ ИТЕРАЦИЯ
		if (!$dir) 
		{	
			// По умолчанию родительская от текущей дирректории
			$dir = str_replace($top_dir, '', __DIR__);
			$dir = str_replace('fwe', '', $dir);
		
			// Задаем корневую
			$dir = 'sites/em/sahmatka/fw';
			$dir = trim($dir, '/');

			print $dir;
		}

		$dirx =   $top_dir . '/' . $dir . '/';

		$dir_arr = scandir(  $dirx);

		foreach ($dir_arr as $k => $file)
		if ($file != '.' && $file != '..') {
 
			$datapath = $dir .'/'.$file;
			if($datapath==$this->fpath){$sel = ' tree_file_s ';}else{$sel='';}
			
			if (is_dir($dirx . '/' . $file)) {
				print '<li class="tree_dir"><a href="?ajax=1&f=' . $dir . '/' . $file . '" class="tree_dira">' . $file . '</a>';
				print '<ul>';
				$this->get_ftree($dir . '/' . $file,$level+1);
				print '</ul>';
				print '</li>';
			} elseif (is_file($dirx . '/' . $file)) {
				print '<li class="tree_file "><a href="index.php?ajax=1&act=loadfile&f='.$datapath.'" class="tree_filea '.$sel.'" data-path="'.$datapath.'" >' . $file . $level.'</a></li>';
			}
		}
	}
	
	// Отрисовка дерева файлов в шаблон 
	function print_tree()
	{
		ob_start();
		print '<ul id="browser">';
		 $this->get_ftree();
		print '</ul>';
		return  ob_get_clean();
	}
	
	
	function print_editarea()
	{
		$file_path = $this->top_dir.'/'.$this->fpath;
		ob_start();
		if( file_exists($file_path))
		{	
			// print '<pre>';
			// print_r($_POST);
			// print '</pre>';
			?>
 
			<?
		}
		else
		{
			print 'Ошибка файл не найден';
		}
		return  ob_get_clean();
	}
	
	
	
	
	
	
	
	function get_dir_array()
	{
		
	}
	
	
	
	
	
	
	function act__test()
	{
		$x= get_used_functions_in_code(file_get_contents('index.php')) ;
		$x=functions_in_file('index.php');
		$tokens=token_get_all(file_get_contents('index.php'),true);		
		foreach ($tokens as $token) {
			if (is_array($token)) {
				//echo "Line {$token[2]}: ", token_name($token[0]), " ('{$token[1]}')", PHP_EOL;
			}
		}
		print_r($x);
	}
	
	
	function act__jsoonajaxftree()
	{
		//print 123123123;
		$arr = $this->get_ftree_jsoon($_GET['id']);
		
		print json_encode($arr);
	}
	
	// аякс загрузка файла
	function act__loadfile()
	{
		$file = $_GET['f'];
		
		// $this->save_backupfile($file);
		
		// $this->get_backups_file($file);
		
		
		$puth = $this->top_dir.'/'.$file;
		 
		if(file_exists($puth) && is_file($puth))
		{
			$js_arr=array();
			$ext = pathinfo($puth, PATHINFO_EXTENSION);
			$mime =  mime_content_type($puth);
			$buf = explode('/',$mime);
			
			$js_arr['mime'] = $mime;
			$js_arr['size'] = filesize($puth);
			$js_arr['ext'] = $ext;
 
			if($buf[0]=='text' || $mime=='application/x-empty' || $mime=='application/octet-stream')
			{
				$js_arr['data'] = file_get_contents($puth);
			}
			else{
				$js_arr['data'] = ' Тип файла не поддерживается ';
				$js_arr['data'] .= $mime; 
			}
			
			
			print json_encode($js_arr);
			//print htmlspecialchars(file_get_contents($puth)); 
		}
		
		
	}
	# ОСТОРОЖНО ! РЕАЛЬНО ПИШЕТ!
	function act__savefile()
	{
		$file = $_GET['f'];
		$puth = $this->top_dir.'/'.$file;
		$js_arr=array();
		if(file_exists($puth) && is_file($puth))
		{
			//$fd = fopen($puth, 'w') or die("не удалось создать файл");
			//$str = $_POST['content'];
			//fwrite($fd, $str);
			//fclose($fd);
		}
		else{
				$js_arr['error'] = 'Нет файла по указанному пути';
		}
		
		$js_arr['status'] = 'ok';
		print json_encode($js_arr);
		//print_r($_POST);
		//print_r($_GET);
	}
	
	
	
	############### БЕКАПЫ
	//Сооздаем патч
	function create_path($puth,$base='')
	{
		if(!$base){ $base = $this->top_dir; }
		$puth = str_replace( $base ,'', $puth );
		$arr = explode('/',$puth);
		
		$existdirstr = '';
		$i=0;
		foreach($arr as $k=>$v)
		{
			if($i>0){ $existdirstr.='/'; }
			$existdirstr.=$v;
			if($existdirstr)
			{
				$x=$base.$existdirstr;
			
				if( @is_dir($x)  ) 
				{
					// print $x.' - есть<br/>';
					continue; 
				}
				else 
				{
					 //print $x.'-НЕТ пробуем создать '.$x; print '<br/>';			
				 	 if (!mkdir($base.$existdirstr)) {	
						die(' Не удалось создать директорию "'.$x.'"');	
					 }
					 else{
						 //print ' Создана дирректория   "'.$x.'"';
					 }
				}
			}
			$i++;
		}
	}
	
	 /// Получить все бекапы файла с размерами!
	 function get_backups_file($orig)
	 {
		 $orig_dir = dirname($orig);
		 
		  $backup_dir = __DIR__.'/backup/'.$orig_dir;
		 $arr = scandir($backup_dir);
		 
		 foreach($arr as $k=>$v)
		 {
			$nf = $backup_dir.$v;
			if(is_file($nf))  
			{
				print $nf.'<br/>';
			}
			else{
				print $nf.'<br/>';
			}
		 }
		 
	 }
	 
	 
	// Сохраняем бекап с относительного пути к файлу
	function save_backupfile($orig)
	{
		 
		$orig_dir = dirname($orig);
	 
		$backup_dir = __DIR__.'/backup/'.$orig_dir;
		
		$this->create_path($backup_dir);
		//datestamp =  date("y.m.d_H:i:s"); 
		$datestamp = time(); 
		print  $new_filename =  $datestamp.'__'.pathinfo($orig, PATHINFO_BASENAME);
		
		
		if (!copy($this->top_dir.'/'.$orig, $backup_dir.'/'.$new_filename)) 
		{
			echo "не удалось скопировать $file...\n";
		}
		else{
			print 'файл скопирован';
		}

	}
	###############
	
	
	function act__index()
	{
		global $fw_tplx;
 
		//$fw_tplx['leftpanel'] = $this->print_tree();
		$fw_tplx['leftpanel'] ='<b style="font-size:12px; color:#eee;">/'.$this->top_dir_editor.'/</b>';
		 
	}
	
	
	
	
	
	
	
	
 
}


 
 
 
 
 


 
 
 




		
		
		
		
 
		
class fw_tpl
{
	function attr($name)
	{
		if( !isset($GLOBALS['fw_tplx']) ){$GLOBALS['tpl']=array();}
	 
		
		if( isset($GLOBALS['fw_tplx'][$name] ) && $GLOBALS['fw_tplx'][$name] )
		{
			return  $GLOBALS['fw_tplx'][$name];
		}
		else
		{
			return 'НЕТ ПЕРЕМЕННОЙ "'.$name.'" ';
		}
	}
}
$fw_tpl = new fw_tpl();



// Упрощенный роутер без указания контроллера (все в одном классе)
class router_fwe
{
	public $ctr_get = 'ctr'; 
	public $act_get = 'act'; 
	
	// выполняем экшен и выводим контент
	function action_content( $action=''  )
	{
		if( !isset($action) || !$action && isset( $_GET[$this->act_get] ) ){$action=$_GET[$this->act_get];}
		if(!$action){ $action = 'index';}
		$class='fwe';
		$method = 'act__'.$action; // метод класса
		if(method_exists($class,$method))
		{
 
			$obj = new $class();
			$obj -> $method();
		}
		else
		{
			print 'no method';
		}
		return true;
	}
}
$r = new router_fwe();
$r->action_content();
 
 if(!isset($_GET['ajax']))
 {
 include('tpl.php');
 }
		


 





 